repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/anderseknert/pre-commit-opa
    rev: v1.5.1
    hooks:
    - id: opa-fmt
      args: [ -w ]
    - id: opa-check
    - id: opa-test
      args: ['policies/', 'utils/']
  - repo: https://github.com/StyraInc/regal
    rev: v0.35.1
    hooks:
      - id: regal-lint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      files: ^.*\.(rego|tf|md|yaml|yml)$
