site_name: Policy Library For Secure AWS Infrastructure
site_url: https://github.com/nhammadi/policy-library-opa-aws-terraform
site_description: Comprehensive OPA policies that can be used to establish secure Terraform configuration for Amazon Web Services infrastructure.
docs_dir: docs/
repo_name: nhammadi/policy-library-opa-aws-terraform
repo_url: https://github.com/nhammadi/policy-library-opa-aws-terraform
extra:
  generator: false
extra_css:
  - css/extra.css
plugins:
  - search:
      lang:
        - en
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - attr_list
theme:
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  language: en
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.sections
    - navigation.top
nav:
- Home:
  - Welcome: index.md
- Policies:
  - APIGateway V2:
    - enable-access-logs: policies/apigatewayv2-enable-access-logs.md
  - AppSync:
    - enable-at-rest-encryption: policies/appsync-enable-at-rest-encryption.md
    - enable-in-transit-encryption: policies/appsync-enable-in-transit-encryption.md
  - Athena:
    - enable-logging: policies/athena-enable-logging.md
  - DynamoDB:
    - enable-dax-in-transit-encryption: policies/dynamodb-dax-enable-in-transit-encryption.md
    - enable-dax-at-rest-encryption: policies/dynamodb-dax-enable-at-rest-encryption.md
  - DMS:
    - enable-auto-minor-version-upgrade: policies/dms-enable-auto-minor-version-upgrade.md
    - use-ssl: policies/dms-use-ssl.md
    - disable-public-access: policies/dms-disable-public-access.md
  - EFS:
    - enable-at-rest-encryption: policies/efs-enable-at-rest-encryption.md
  - ECR:
    - enable-private-image-scanning: policies/ecr-enable-private-image-scanning.md
    - configure-private-lifecycle-policy: policies/ecr-configure-private-lifecycle-policy.md
  - ECS:
    - enable-container-insights: policies/ecs-enable-container-insights.md
    - disable-taskset-assign-public-ip: policies/ecs-disable-taskset-assign-public-ip.md
  - ElastiCache:
    - enable-auto-minor-version-upgrade: policies/elasticache-enable-auto-minor-version-upgrade.md
  - EventBridge:
    - attach-resource-based-policy: policies/eventbridge-attach-resource-based-policy
  - Firehose:
    - enable-at-rest-encryption: policies/firehose-enable-server-side-encryption.md
  - Glue:
    - spark-job-supported-version: policies/glue-spark-job-supported-version.md
  - Kinesis:
    - enable-server-side-encryption: policies/kinesis-enable-server-side-encryption.md
  - KMS:
    - enable-key-rotation: policies/kms-enable-key-rotation.md
  - MQ:
    - enable-auto-minor-version-upgrade: policies/mq-enable-auto-minor-version-upgrade.md
  - OpenSearch:
    - enable-node-to-node-encryption: policies/opensearch-enable-node-to-node-encryption.md
  - Neptune:
    - enable-copy-tags-to-snapshots: policies/neptune-enable-copy-tags-to-snapshots.md
  - Redshift:
    - disable-public-access: policies/redshift-disable-public-access.md
    - enable-version-upgrade: policies/redshift-enable-version-upgrade.md
  - RDS:
    - enable-auto-minor-version-upgrade: policies/rds-enable-auto-minor-version-upgrade.md
  - SQS:
    - enable-at-rest-encryption: policies/sqs-enable-at-rest-encryption.md
  - Step Functions:
    - enable-logging: policies/stepfunction-enable-logging.md
